"""second  Migrate

Revision ID: aebc6114b193
Revises: 18fa9cf9e4a1
Create Date: 2023-10-20 09:02:21.737760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebc6114b193'
down_revision = '18fa9cf9e4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('post', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judul')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blogs')
    # ### end Alembic commands ###
